quiz/urls.py
__author__ = 'wbeard'

from django.conf.urls import url
from django.views.generic import TemplateView
from quiz.views import ScoresView

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='quiz_list'),
    url(r'^scores/', ScoresView.as_view(), name='scores'),
]

thronesquiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quiz/', include('quiz.urls', namespace="quiz")),
]

quiz/models.py
from django.db import models

from django.db.models import IntegerField


class Question(models.Model):
    content = models.CharField(max_length=300)


    def __str__(self):
        return self.content


class Answer(models.Model):
    content = models.CharField(max_length=300)
    correct = models.BooleanField()
    question = models.ForeignKey(Question)

    def __str__(self):
        return self.content


class User(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.content


class Score(models.Model):
    correct = IntegerField()
    user = models.ForeignKey(User)

    def __str__(self):
        return self.content

quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, request
from django.template import RequestContext, loader

from quiz.models import Question, Answer
# Create your views here.


class IndexView(generic.ListView):
    context_object_name = 'quiz_list'
    template_name = 'quiz/index.html'
    queryset = Question.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['answers'] = Answer.objects.all()
        return context


class ScoresView(TemplateView):
    template_name = 'quiz/scores.html'
    queryset = Question.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ScoresView, self).get_context_data(**kwargs)
        context['answers'] = Answer.objects.all()
        return context

    @property
    def get_score(request):
        num_questions = 3
        correct = 0
        selected_answer_id = Question.objects.all().answer_set.get(pk=request.POST['answer.pk'])
        print selected_answer_id
        # return 0 if not request.POST['answer.pk']
        for question_id,answer_pk in request.POST['answer.pk']:
            setting_question = Question.objects.get(question_id)
            correct_answer_id = setting_question.answer_set.filter(correct=True).first().pk
            if correct_answer_id == int(selected_answer_id):
                correct += 1
            return correct/num_questions

quiz/templates/quiz/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />


<h1>Quiz of Thrones</h1>

<form action="{%  url 'quiz:scores' %}" method="post">{% csrf_token %}

{% for question in quiz_list %}

    <ul>
        <li>{{ question.content }} </li>
    </ul>
    <br>

    {% for answer in question.answer_set.all %}

        <input type="radio" name = "answer{{ question.id }}" id="{{ answer.question.id }}" value="{{ answer.pk }}" class='answers'>
        <ul>
            <li><label class="answers">{{ answer.content }}</label></li>
        </ul>

    {% endfor %}
    <br>


{% endfor %}

<input type="submit" value="Submit"/>

</form>

quiz/templates/quiz/scores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>hello, world. this is the scores page.</h1>
</body>
</html>